/*
 * FLUX OS — Bytecode Virtual Machine
 *
 * The FLUX VM is a register-based virtual machine with 64 general-purpose
 * registers, designed to execute FLUX bytecode as a first-class citizen
 * of the operating system. It runs in kernel-space for performance and
 * supports sandboxed user-space execution for untrusted code.
 *
 * Key Design Decisions:
 *   - 64 registers (R0-R63) — matches FLUX specification
 *   - R0 is hardwired to zero (optimization target)
 *   - R1-R7 are argument/temporary registers (caller-saved)
 *   - R8-R15 are callee-saved
 *   - R56-R63 are special-purpose (SP, BP, PC, FLAGS, etc.)
 *   - Memory regions for isolated execution (agent sandboxes)
 *   - Cycle-accurate profiling for adaptive optimization
 *
 * The VM is used by:
 *   - Agent runtime for executing agent logic
 *   - Self-compiler for testing generated bytecode
 *   - Process scheduler for bytecode processes
 *   - Hardware abstraction for platform-agnostic code
 */

#ifndef FLUX_VM_H
#define FLUX_VM_H

#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include "flux/kernel.h"

#ifdef __cplusplus
extern "C" {
#endif

/* ========================================================================
 * VM Register Definitions
 * ======================================================================== */

#define FLUX_VM_NUM_REGS      64

/* Special register indices */
#define FLUX_REG_ZERO         0   /* Always zero */
#define FLUX_REG_RA           1   /* Return address */
#define FLUX_REG_SP           2   /* Stack pointer */
#define FLUX_REG_BP           3   /* Base pointer */
#define FLUX_REG_PC           4   /* Program counter (implicit in most ops) */
#define FLUX_REG_FLAGS        5   /* Flags register */
#define FLUX_REG_FP           6   /* Frame pointer */
#define FLUX_REG_T0           7   /* Temporary */

/* Callee-saved registers */
#define FLUX_REG_S0           8
#define FLUX_REG_S1           9
#define FLUX_REG_S2           10
#define FLUX_REG_S3           11
#define FLUX_REG_S4           12
#define FLUX_REG_S5           13
#define FLUX_REG_S6           14
#define FLUX_REG_S7           15

/* Argument registers */
#define FLUX_REG_A0           16
#define FLUX_REG_A1           17
#define FLUX_REG_A2           18
#define FLUX_REG_A3           19

/* Temporaries */
#define FLUX_REG_T1           20
#define FLUX_REG_T2           21
#define FLUX_REG_T3           22

/* Agent registers (R32-R47) */
#define FLUX_REG_AGENT_BASE   32

/* Special-purpose (R56-R63) */
#define FLUX_REG_VMSTATE      56  /* VM state flags */
#define FLUX_REG_CYCLE_COUNT  57  /* Cycle counter */
#define FLUX_REG_REGION_BASE  58  /* Current memory region base */
#define FLUX_REG_REGION_SIZE  59  /* Current memory region size */
#define FLUX_REG_SYSCALL_NUM  60  /* Syscall number */
#define FLUX_REG_ERROR_CODE   61  /* Last error */
#define FLUX_REG_CAPABILITY   62  /* Current capability */
#define FLUX_REG_TRAP_HANDLER 63  /* Trap handler address */

/* ========================================================================
 * VM Flags
 * ======================================================================== */

#define FLUX_FLAG_ZERO        (1 << 0)
#define FLUX_FLAG_NEGATIVE    (1 << 1)
#define FLUX_FLAG_CARRY       (1 << 2)
#define FLUX_FLAG_OVERFLOW    (1 << 3)
#define FLUX_FLAG_EQUAL       (1 << 4)
#define FLUX_FLAG_LESS        (1 << 5)
#define FLUX_FLAG_GREATER     (1 << 6)
#define FLUX_FLAG_TRAP        (1 << 7)

/* ========================================================================
 * VM States
 * ======================================================================== */

typedef enum {
    FLUX_VM_IDLE      = 0,
    FLUX_VM_RUNNING   = 1,
    FLUX_VM_HALTED    = 2,
    FLUX_VM_TRAPPED   = 3,
    FLUX_VM_ERROR     = 4,
    FLUX_VM_WAITING   = 5,
} flux_vm_state_t;

/* ========================================================================
 * Opcode Categories
 * ======================================================================== */

typedef enum {
    FLUX_OP_CAT_NONE     = 0,
    FLUX_OP_CAT_ARITH    = 1,   /* Arithmetic operations */
    FLUX_OP_CAT_LOGIC    = 2,   /* Logical/bitwise operations */
    FLUX_OP_CAT_COMPARE  = 3,   /* Comparison operations */
    FLUX_OP_CAT_BRANCH   = 4,   /* Branch/jump operations */
    FLUX_OP_CAT_MEMORY   = 5,   /* Load/store operations */
    FLUX_OP_CAT_STACK    = 6,   /* Push/pop operations */
    FLUX_OP_CAT_CALL     = 7,   /* Function call operations */
    FLUX_OP_CAT_AGENT    = 8,   /* A2A agent operations */
    FLUX_OP_CAT_IO       = 9,   /* Input/output operations */
    FLUX_OP_CAT_SYSTEM   = 10,  /* System/VM control operations */
    FLUX_OP_CAT_FLUX     = 11,  /* FLUX-specific operations */
    FLUX_OP_CAT_EXT      = 12,  /* Extension operations */
} flux_op_cat_t;

/* ========================================================================
 * VM Instruction (decoded format)
 * ======================================================================== */

typedef struct {
    uint8_t  opcode;
    uint8_t  rd;        /* Destination register */
    uint8_t  rs1;       /* Source register 1 */
    uint8_t  rs2;       /* Source register 2 */
    int32_t  imm;       /* Immediate value */
    uint32_t target;    /* Branch/call target (bytecode offset) */
} flux_vm_insn_t;

/* ========================================================================
 * Memory Region (Sandboxed)
 * ======================================================================== */

#define FLUX_REGION_MAX      16

typedef struct {
    flux_addr_t  base;
    flux_size_t  size;
    uint8_t     *data;
    bool         active;
    bool         readonly;
    flux_pid_t   owner;
    char         name[32];
} flux_vm_region_t;

/* ========================================================================
 * VM Instance
 * ======================================================================== */

#define FLUX_VM_MAX_CALL_DEPTH  256
#define FLUX_VM_MAX_BREAKPOINTS 64
#define FLUX_VM_TRACE_BUFFER    4096

typedef struct {
    /* State */
    flux_vm_state_t  state;
    uint8_t          error_code;

    /* Registers */
    uint64_t         regs[FLUX_VM_NUM_REGS];

    /* Memory */
    flux_vm_region_t regions[FLUX_REGION_MAX];
    int              active_region;

    /* Stack */
    uint64_t        *stack;
    flux_size_t      stack_size;
    flux_size_t      stack_ptr;

    /* Call stack */
    uint64_t         call_stack[FLUX_VM_MAX_CALL_DEPTH];
    int              call_depth;

    /* Bytecode */
    const uint8_t   *bytecode;
    flux_size_t      bytecode_len;
    flux_size_t      pc;

    /* Execution tracking */
    uint64_t         cycle_count;
    uint64_t         insn_count;
    uint32_t         breakpoint_addrs[FLUX_VM_MAX_BREAKPOINTS];
    int              num_breakpoints;

    /* Trace buffer */
    struct {
        uint32_t    pc;
        uint8_t     opcode;
        uint64_t    regs[8]; /* R0-R7 snapshot */
    } trace[FLUX_VM_TRACE_BUFFER];
    int              trace_idx;
    bool             tracing;

    /* Profiling */
    uint64_t         op_counts[256]; /* Count per opcode */
    uint64_t         last_op_cycles;

    /* Owner process */
    flux_pid_t       owner_pid;
    bool             sandboxed;
} flux_vm_t;

/* ========================================================================
 * VM Initialization & Control
 * ======================================================================== */

flux_status_t  flux_vm_init(flux_vm_t *vm);
flux_status_t  flux_vm_reset(flux_vm_t *vm);
flux_status_t  flux_vm_destroy(flux_vm_t *vm);

/* Bytecode loading */
flux_status_t  flux_vm_load(flux_vm_t *vm, const uint8_t *bytecode, flux_size_t len);
flux_status_t  flux_vm_load_from_file(flux_vm_t *vm, const char *path);

/* Execution */
flux_status_t  flux_vm_step(flux_vm_t *vm);
flux_status_t  flux_vm_run(flux_vm_t *vm, flux_size_t max_cycles);
flux_status_t  flux_vm_halt(flux_vm_t *vm);
flux_status_t  flux_vm_trap(flux_vm_t *vm, uint8_t trap_code);

/* Memory regions */
int            flux_vm_region_create(flux_vm_t *vm, const char *name,
                                     flux_size_t size, bool readonly);
void          *flux_vm_region_data(flux_vm_t *vm, int region_id);
flux_status_t  flux_vm_region_destroy(flux_vm_t *vm, int region_id);

/* Breakpoints & Debugging */
flux_status_t  flux_vm_breakpoint_set(flux_vm_t *vm, uint32_t addr);
flux_status_t  flux_vm_breakpoint_clear(flux_vm_t *vm, uint32_t addr);
void           flux_vm_trace_enable(flux_vm_t *vm, bool enable);
void           flux_vm_trace_dump(flux_vm_t *vm);

/* Profiling */
void           flux_vm_profile_reset(flux_vm_t *vm);
void           flux_vm_profile_dump(flux_vm_t *vm);

/* Register access */
static inline uint64_t flux_vm_get_reg(flux_vm_t *vm, uint8_t r) {
    return (r == FLUX_REG_ZERO) ? 0 : vm->regs[r];
}
static inline void flux_vm_set_reg(flux_vm_t *vm, uint8_t r, uint64_t val) {
    if (r != FLUX_REG_ZERO) vm->regs[r] = val;
}
static inline void flux_vm_set_flags(flux_vm_t *vm, uint64_t a, uint64_t b) {
    vm->regs[FLUX_REG_FLAGS] = 0;
    if (a == b) vm->regs[FLUX_REG_FLAGS] |= FLUX_FLAG_EQUAL;
    if (a < b)  vm->regs[FLUX_REG_FLAGS] |= FLUX_FLAG_LESS;
    if (a > b)  vm->regs[FLUX_REG_FLAGS] |= FLUX_FLAG_GREATER;
    if (a == 0) vm->regs[FLUX_REG_FLAGS] |= FLUX_FLAG_ZERO;
    if ((int64_t)a < 0) vm->regs[FLUX_REG_FLAGS] |= FLUX_FLAG_NEGATIVE;
}

#ifdef __cplusplus
}
#endif

#endif /* FLUX_VM_H */
